name: device_repository
description: Dart package which manages the user domain.
version: 1.0.0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  equatable: ^1.2.0
  meta: ^1.1.8
  http: ^0.12.2
